# Generated by Django 3.2.5 on 2021-07-29 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='saleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('cosName', models.CharField(default=False, max_length=10)),
                ('phone', models.CharField(default=False, max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('serviceName', models.CharField(default=False, max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('usr', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='expanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('buyerName', models.CharField(default=False, max_length=100)),
                ('buyerPhone', models.CharField(default=False, max_length=12)),
                ('buyerEmail', models.EmailField(max_length=254)),
                ('serviceName', models.CharField(default=False, max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('usr', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
