# Generated by Django 3.2.5 on 2021-07-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210731_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expancedata',
            name='price',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='price',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
