# Generated by Django 3.2.5 on 2021-07-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210731_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expancedata',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
