# Generated by Django 3.2.5 on 2021-08-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210731_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default='', max_length=12)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(default='', max_length=50)),
                ('quary', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
