# Generated by Django 3.2.8 on 2021-12-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_contactus_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expancedata',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
