# Generated by Django 4.2.4 on 2023-08-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211209_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expancedata',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='price',
            field=models.IntegerField(),
        ),
    ]
